apiVersion: aws-light/v1
kind: Secrets
secrets:
  my-secret: hello-from-secret
  another-secret: second-secret-value
---
apiVersion: aws-light/v1
kind: Service
metadata:
  name: hello-service
spec:
  image: aws-light/hello-service:latest
  replicas: 2
  minReplicas: 2
  maxReplicas: 3
  cpuRequest: 0.2
  memoryRequestMb: 128
  port: 8000
  healthCheckPath: /health
  env: {}
  secretRefs:
    - my-secret
    - another-secret
